name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: echo Building...

    - uses: actions/upload-artifact@v2
      with:
        name: bundle1.js.map
        path: test/bundle1.js.map
    - uses: actions/upload-artifact@v2
      with:
        name: bundle2.js.map
        path: test/bundle2.js.map

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2

    - name: Nofity rollbar deploy start
      uses: ./
      id: rollbar_pre_deploy
      with:
        environment: 'production'
        version: ${{ github.sha }}
        status: 'started'
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        ROLLBAR_USERNAME: ${{ github.actor }}

    - uses: actions/download-artifact@v2
      with:
        name: bundle1.js.map
    - uses: actions/download-artifact@v2
      with:
        name: bundle2.js.map    

    # Print Rollbar's deploy id
    - name: Get the Rollbar deploy id
      run: echo Deploy created with id ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}

    - name: Deploy
      run: echo Deploying...

    - name: Nofity rollbar deploy succeeded
      uses: ./
      id: rollbar_post_deploy
      with:
        environment: 'production'
        version: ${{ github.sha }}
        status: 'succeeded'
        source_map: bundle1.js.map bundle2.js.map
        minified_url: https://www.example.com/abc/bundle1.js https://www.example.com/xyz/bundle2.js
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
        ROLLBAR_USERNAME: ${{ github.actor }}
        
    # Print Rollbar's deploy id
    - name: Verify both outputs are the same.
      run: if [[ "$START_DEPLOY_ID" != "$FINISH_DEPLOY_ID" ]]; then exit 1; fi
      env:
        START_DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
        FINISH_DEPLOY_ID: ${{ steps.rollbar_post_deploy.outputs.deploy_id }}
